config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  resources :cars
  resources :rentals
  resources :users
  resources :locations
  root 'pages#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= content_for(:title) || "Car Rental System" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag :app %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%=link_to 'Home', root_path, class: 'nav-link px-2 text-white' %></li>
          <li><%=link_to 'Users', users_path, class: 'nav-link px-2 text-white' %></li>
          <li><%=link_to 'Locations', locations_path, class: 'nav-link px-2 text-white' %></li>
          <li><%=link_to 'Cars', cars_path, class: 'nav-link px-2 text-white' %></li>
          <li><%=link_to 'Rentals', rentals_path, class: 'nav-link px-2 text-white' %></li>
        </ul>
      </nav>
    </div>
  </header>

  <main class="container mt-3">
    <% flash.each do |key, value| %>
      <%= tag.div value, class: "alert alert-#{key}", role: 'alert' %>
    <% end %>

    <%= yield %>
  </main>
  </body>
</html>